// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using efcorepractice;

namespace efcorepractice.Migrations
{
    [DbContext(typeof(efcoreDBContext))]
    [Migration("20191015065616_firstinit")]
    partial class firstinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("efcorepractice.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyPrefix");

                    b.Property<DateTime>("DBServerDateTime");

                    b.Property<int>("DBServerUserID");

                    b.Property<string>("Name");

                    b.Property<int>("ParentCompanyID");

                    b.HasKey("ID");

                    b.ToTable("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
